# Generated by Django 6.0.2 on 2026-03-03 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='subcategoryid',
        ),
        migrations.AddField(
            model_name='community',
            name='categoryid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.category'),
            preserve_default=False,
        ),
    ]
