# Generated by Django 4.2.16 on 2026-03-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_communityinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/backgrounds/'),
        ),
    ]
