# Generated by Django 6.0.2 on 2026-03-03 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('chatid', models.AutoField(primary_key=True, serialize=False)),
                ('senderid', models.IntegerField(max_length=50)),
                ('receiverid', models.IntegerField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
                ('senddt', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='community',
            fields=[
                ('communityid', models.AutoField(primary_key=True, serialize=False)),
                ('communitytitle', models.TextField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('discription', models.TextField(max_length=1000)),
                ('createddt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('stateid', models.AutoField(primary_key=True, serialize=False)),
                ('statename', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='communityMessage',
            fields=[
                ('communityMessageid', models.AutoField(primary_key=True, serialize=False)),
                ('senderid', models.IntegerField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
                ('senddt', models.DateTimeField(auto_now=True)),
                ('communityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.community')),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('cityname', models.TextField(max_length=50)),
                ('stateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.state')),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('subcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('subcategoryname', models.TextField(max_length=50)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='subcategoryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subcategory'),
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('profile', models.ImageField(upload_to='assets/images/user/')),
                ('bio', models.TextField(max_length=1000)),
                ('gender', models.TextField(max_length=10)),
                ('dob', models.DateField()),
                ('registrationdt', models.DateTimeField(auto_now=True)),
                ('cityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.city')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('postid', models.AutoField(primary_key=True, serialize=False)),
                ('posttitle', models.TextField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('description', models.TextField(max_length=1000)),
                ('createddt', models.DateTimeField(auto_now=True)),
                ('isapproved', models.BooleanField(default=False)),
                ('communityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.community')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('likeid', models.AutoField(primary_key=True, serialize=False)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.post')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('imageid', models.AutoField(primary_key=True, serialize=False)),
                ('addeddt', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('communityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.community')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='follow',
            fields=[
                ('followid', models.AutoField(primary_key=True, serialize=False)),
                ('followerid', models.IntegerField(max_length=50)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='communitymember',
            fields=[
                ('communitymemberid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(max_length=50)),
                ('addeddt', models.DateTimeField(auto_now=True)),
                ('communityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.community')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='communityAdmins',
            fields=[
                ('communityAdminsid', models.AutoField(primary_key=True, serialize=False)),
                ('addedbyuserid', models.IntegerField(max_length=50)),
                ('addeddt', models.DateTimeField(auto_now=True)),
                ('communityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.community')),
                ('adminid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('commentid', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=1000)),
                ('createddt', models.DateTimeField(auto_now=True)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.post')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
