# Generated by Django 6.0.2 on 2026-03-03 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_community_subcategoryid_community_categoryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityInvite',
            fields=[
                ('inviteid', models.AutoField(primary_key=True, serialize=False)),
                ('senderid', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('createddt', models.DateTimeField(auto_now=True)),
                ('communityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.community')),
                ('receiverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
