# Generated by Django 6.0.2 on 2026-03-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_communityinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10),
        ),
    ]
