# Generated by Django 6.0.2 on 2026-03-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_communitymember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='can_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='post_request_status',
            field=models.IntegerField(default=0),
        ),
    ]
