# Generated by Django 4.2.16 on 2026-03-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_communitymember_can_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/backgrounds/'),
        ),
    ]
