# Generated by Django 6.0.2 on 2026-03-13 10:06

import django.db.models.deletion
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_community_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(validators=[user.models.no_future_date]),
        ),
        migrations.CreateModel(
            name='story',
            fields=[
                ('storyid', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='stories/')),
                ('createddt', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
