# Generated by Django 6.0.2 on 2026-03-13 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_dob_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorySeen',
            fields=[
                ('seenid', models.AutoField(primary_key=True, serialize=False)),
                ('seendt', models.DateTimeField(auto_now_add=True)),
                ('storyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.story')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
