# Generated by Django 4.2.16 on 2026-03-14 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_storyseen'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('blogid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=10000)),
                ('image', models.ImageField(upload_to='blogs/')),
                ('createddt', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('categoryid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.category')),
            ],
        ),
    ]
