# Generated by Django 6.0.2 on 2026-03-14 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_follow_createddt_like_createddt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='communityid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.community'),
        ),
    ]
