# Generated by Django 4.2.7 on 2026-03-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_post_communityid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
