# Generated by Django 6.0.2 on 2026-03-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='cityname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='community',
            name='communitytitle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='posttitle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='state',
            name='statename',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategoryname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
