# Generated by Django 6.0.2 on 2026-03-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_blog_title_alter_category_categoryname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityadmins',
            options={'verbose_name': 'Community Admin', 'verbose_name_plural': 'Community Admins'},
        ),
        migrations.AlterModelOptions(
            name='communitymember',
            options={'verbose_name': 'Community Member', 'verbose_name_plural': 'Community Members'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
    ]
