# Generated by Django 6.0.2 on 2026-03-24 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_communityadmins_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='meetup',
            fields=[
                ('meetupid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('meetup_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('meeting_date', models.DateTimeField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='meetups/')),
                ('createddt', models.DateTimeField(auto_now_add=True)),
                ('communityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.community')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
