# Generated by Django 6.0.2 on 2026-03-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_meetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='meetup_type',
            field=models.CharField(choices=[('internal', 'Internal Video Meeting'), ('external', 'External Link (Google Meet, Zoom, etc.)'), ('offline', 'Offline (In-Person)')], default='offline', max_length=10),
        ),
    ]
