# Generated by Django 6.0.2 on 2026-03-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_meetup_meetup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='location_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
