# Generated by Django 6.0.2 on 2026-03-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_meetup_location_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='location_link',
        ),
    ]
