# Generated by Django 4.2.7 on 2026-03-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.AddField(
            model_name='meetup',
            name='meeting_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
