# Generated by Django 4.2.7 on 2026-03-28 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_delete_contactmessage_meetup_meeting_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='member_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='meetup_member',
            fields=[
                ('meetup_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('joineddt', models.DateTimeField(auto_now_add=True)),
                ('meetupid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.meetup')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'Meetup Member',
                'verbose_name_plural': 'Meetup Members',
                'unique_together': {('meetupid', 'userid')},
            },
        ),
    ]
