# Generated by Django 6.0.2 on 2026-03-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_meetup_member_limit_meetup_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
