# Generated by Django 6.0.2 on 2026-03-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_communitymessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='receiverid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='communityadmins',
            name='addedbyuserid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='communitymessage',
            name='senderid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='follow',
            name='followerid',
            field=models.IntegerField(),
        ),
    ]
