# Generated by Django 6.0.2 on 2026-03-29 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_user_last_seen_alter_chat_receiverid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.post'),
        ),
    ]
