# Generated by Django 6.0.2 on 2026-03-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_chat_shared_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='community',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
