# Generated by Django 4.2.7 on 2026-03-31 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('theme_color', models.CharField(default='blue', max_length=20)),
                ('font_size', models.CharField(default='medium', max_length=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('meetup_reminders', models.BooleanField(default=True)),
                ('community_updates', models.BooleanField(default=True)),
                ('notification_frequency', models.CharField(default='instant', max_length=20)),
                ('language', models.CharField(default='English', max_length=20)),
                ('currency_format', models.CharField(default='USD', max_length=10)),
                ('date_time_format', models.CharField(default='MM/DD/YYYY', max_length=20)),
                ('profile_visibility', models.CharField(default='public', max_length=10)),
                ('data_usage_consent', models.BooleanField(default=True)),
                ('ai_recommendations', models.BooleanField(default=True)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='user.user')),
            ],
        ),
    ]
