# Generated by Django 4.2.7 on 2026-06-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='posttitle',
            field=models.CharField(max_length=200),
        ),
    ]
