# Generated by Django 4.2.7 on 2026-06-12 09:58

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_community_price_alter_post_posttitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to=user.models.blogs_path),
        ),
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.chat_images_path),
        ),
        migrations.AlterField(
            model_name='community',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.background_images_path),
        ),
        migrations.AlterField(
            model_name='community',
            name='thumbnail',
            field=models.ImageField(upload_to=user.models.images_path),
        ),
        migrations.AlterField(
            model_name='communitymessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.chat_images_path),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=user.models.images_path),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.meetups_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to=user.models.images_path),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to=user.models.stories_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(upload_to=user.models.user_profile_path),
        ),
    ]
