from django.urls import path
from . import views
urlpatterns = [
    path('',views.home,name="home"),
    path('signup/',views.signup,name="signup"),
    path('signin/',views.signin,name="signin"),
    path('verify-2fa/',views.verify_2fa,name="verify_2fa"),
    path('logout/',views.logout_view,name="logout"),
    path('forgot-password/', views.forgot_password, name="forgot_password"),
    path('group/', views.group, name="group"),
    path('create-group/', views.create_group, name="create_group"),
    path('join-group/<int:community_id>/', views.join_group, name='join_group'),
    path('community/<int:community_id>/payment/', views.community_payment, name='community_payment'),
    path('community/<int:community_id>/verify-payment/', views.verify_payment, name='verify_payment'),
    path('users/', views.users_list, name='users_list'),
    path('follow/<int:target_userid>/', views.toggle_follow, name='toggle_follow'),
    path('invite_user/<int:target_userid>/', views.invite_user, name='invite_user'),
    path('invitations/', views.invitations_list, name='invitations_list'),
    path('invitation/respond/<int:inviteid>/<str:action>/', views.respond_invite, name='respond_invite'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/delete/', views.delete_profile, name='delete_profile'),
    path('profile/<int:target_userid>/', views.user_profile, name='user_profile'),
    path('profile/', views.user_profile, name='my_profile'),
    path('settings/', views.settings_view, name='settings'),
    path('buzz/', views.buzz, name='buzz'),
    path('buzz/post/add/', views.add_buzz_post, name='add_buzz_post'),
    path('buzz/post/<int:post_id>/edit/', views.edit_buzz_post, name='edit_buzz_post'),
    path('buzz/post/<int:post_id>/delete/', views.delete_buzz_post, name='delete_buzz_post'),
    path('chats/', views.chats_list, name='chats'),
    path('chats/delete/<int:chat_id>/', views.delete_chat, name='delete_chat'),
    path('chats/edit/<int:chat_id>/', views.edit_chat, name='edit_chat'),
    # Group Member Management
    path('community/<int:community_id>/edit/', views.edit_community, name='edit_community'),
    path('community/<int:community_id>/members/', views.group_members, name='group_members'),
    path('community/<int:community_id>/members/add/', views.add_member, name='add_member'),
    path('community/<int:community_id>/members/<int:member_id>/promote/', views.promote_member, name='promote_member'),
    path('community/<int:community_id>/members/<int:member_id>/demote/', views.demote_member, name='demote_member'),
    path('community/<int:community_id>/members/<int:member_id>/delete/', views.delete_member, name='delete_member'),
    path('community/<int:community_id>/members/<int:member_id>/accept/', views.accept_join_request, name='accept_join_request'),
    path('community/<int:community_id>/members/<int:member_id>/reject/', views.reject_join_request, name='reject_join_request'),
    path('activity/', views.activity, name='activity'),
    # Community Posts, Comments, Likes
    path('community/<int:community_id>/', views.community_detail, name='community_detail'),
    path('community/<int:community_id>/chat/', views.community_chat, name='community_chat'),
    path('community/<int:community_id>/chat/send/', views.send_community_message, name='send_community_message'),
    path('community/<int:community_id>/post/add/', views.add_post, name='add_post'),
    path('community/<int:community_id>/post/request-permission/', views.request_post_permission, name='request_post_permission'),
    path('community/<int:community_id>/post/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('community/<int:community_id>/post/<int:post_id>/edit/', views.edit_post, name='edit_post'),
    path('community/<int:community_id>/members/<int:member_id>/approve-post-permission/', views.approve_post_permission, name='approve_post_permission'),
    path('community/<int:community_id>/members/<int:member_id>/reject-post-permission/', views.reject_post_permission, name='reject_post_permission'),
    path('post/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('post/<int:post_id>/like/', views.toggle_like, name='toggle_like'),
    path('post/<int:post_id>/share/', views.share_post_to_user, name='share_post'),
    path('api/share-targets/', views.get_share_targets, name='get_share_targets'),
    path('api/cities/<int:state_id>/', views.get_cities_by_state, name='get_cities_by_state'),
    path('add-story/', views.add_story, name='add_story'),
    path('mark-story-seen/', views.mark_story_seen, name='mark_story_seen'),
    path('delete-story/', views.delete_story, name='delete_story'),
    path('blogs/', views.blog_list, name='blog_list'),
    path('blog/<int:blog_id>/', views.blog_detail, name='blog_detail'),
    path('add-blog/', views.add_blog, name='add_blog'),
    path('blog/<int:blog_id>/edit/', views.edit_blog, name='edit_blog'),
    path('blog/<int:blog_id>/delete/', views.delete_blog, name='delete_blog'),
    path('contact-us/', views.contact_us, name='contact_us'),
    # Google OAuth
    path('auth/google/', views.google_login, name='google_login'),
    path('auth/google/callback/', views.google_callback, name='google_callback'),
    # Meetups
    path('meetups/', views.meetup_list, name='meetup_list'),
    path('calendar/', views.calendar_view, name='calendar'),
    path('community/<int:community_id>/meetup/create/', views.create_meetup, name='create_meetup'),
    path('meetup/<int:meetup_id>/', views.meetup_detail, name='meetup_detail'),
    path('meetup/<int:meetup_id>/join-rsvp/', views.join_meetup_rsvp, name='join_meetup_rsvp'),
    path('meetup/<int:meetup_id>/join/', views.join_meeting, name='join_meeting'),
    path('meetup/<int:meetup_id>/delete/', views.delete_meetup, name='delete_meetup'),
    path('add-post/', views.unified_add_post, name='unified_add_post'),
]